# Generated by Django 4.0.4 on 2022-08-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestCrudApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='fullname',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='frnd_code',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='mobile',
        ),
        migrations.AddField(
            model_name='friend',
            name='createdAt',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='dob',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
